name = input("Enter your name: ")
age = int(input("Enter your age: "))
university_name = input("Enter your university name: ")
dept = input("Enter your department: ")
course_name = input("Enter your course name: ")
course_fee = float(input("Enter your course fee: "))
discount_percentage = float(input("Enter the discount percentage: "))
Registration_fee = float(input("Enter the registration fee: "))
discount_Amount = (discount_percentage / 100) * course_fee
total_fee = course_fee - discount_Amount + Registration_fee

print("======================================")
print("\t Student Registration \t")
print("======================================")
print("Student Name         : ", name)
print("Age                  : ", age)
print("University Name      : ", university_name)
print("Department           : ", dept)
print("Course Name          : ", course_name)
print("Course Fee           : ", course_fee)
print("Discount Percentage  : ", discount_percentage)
print("Registration Fee     : ", Registration_fee)
print("Discount Amount      : ", discount_Amount)
print("Total Fee            : ", total_fee)
print("======================================")
print("\t Thank You \t")
print("======================================")